/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajargui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Rosyid Izzulkhaq
 */
public class mahasiswa extends javax.swing.JFrame {
    
    DefaultTableModel model;
    
    private int tgl, bln, thn;
    private String nim, nama, fakultas, jurusan, alamat;
    
    
    /**
     * Creates new form mahasiswa
     */
    public mahasiswa() {
        initComponents();
        
        model = (DefaultTableModel) jTable2.getModel();
        
        jTable2.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tv_nim = new javax.swing.JTextField();
        tv_nama = new javax.swing.JTextField();
        cb_fakultas = new javax.swing.JComboBox<>();
        tv_jurusan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tv_alamat = new javax.swing.JTextArea();
        tv_tgl = new javax.swing.JTextField();
        tv_thn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tv_bln = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA MAHASISWA");
        setBackground(new java.awt.Color(56, 56, 56));
        setForeground(new java.awt.Color(51, 51, 51));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("NIM : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Nama : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Jurusan : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Alamat : ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Fakultas : ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Tgl Lahir : ");

        tv_nim.setBackground(new java.awt.Color(229, 229, 229));
        tv_nim.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_nim.setForeground(new java.awt.Color(56, 56, 56));
        tv_nim.setToolTipText("Masukkan NIM anda");
        tv_nim.setBorder(null);
        tv_nim.setNextFocusableComponent(tv_nama);

        tv_nama.setBackground(new java.awt.Color(229, 229, 229));
        tv_nama.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_nama.setForeground(new java.awt.Color(56, 56, 56));
        tv_nama.setToolTipText("Masukkan Nama Anda");
        tv_nama.setBorder(null);
        tv_nama.setNextFocusableComponent(cb_fakultas);

        cb_fakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FTIE", "FIB", "KEDOKTERAN", "HUMANIORA", "FISIPOL", " " }));
        cb_fakultas.setNextFocusableComponent(tv_jurusan);

        tv_jurusan.setBackground(new java.awt.Color(229, 229, 229));
        tv_jurusan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_jurusan.setForeground(new java.awt.Color(56, 56, 56));
        tv_jurusan.setToolTipText("Masukkan Jurusan Anda");
        tv_jurusan.setBorder(null);
        tv_jurusan.setNextFocusableComponent(tv_alamat);

        tv_alamat.setBackground(new java.awt.Color(229, 229, 229));
        tv_alamat.setColumns(10);
        tv_alamat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_alamat.setForeground(new java.awt.Color(56, 56, 56));
        tv_alamat.setRows(5);
        tv_alamat.setToolTipText("Masukkan Alamat Anda");
        tv_alamat.setBorder(null);
        tv_alamat.setNextFocusableComponent(tv_tgl);
        jScrollPane1.setViewportView(tv_alamat);

        tv_tgl.setBackground(new java.awt.Color(229, 229, 229));
        tv_tgl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_tgl.setForeground(new java.awt.Color(56, 56, 56));
        tv_tgl.setToolTipText("Tanggal Lahir");
        tv_tgl.setBorder(null);
        tv_tgl.setNextFocusableComponent(tv_bln);

        tv_thn.setBackground(new java.awt.Color(229, 229, 229));
        tv_thn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_thn.setForeground(new java.awt.Color(56, 56, 56));
        tv_thn.setToolTipText("Tahun Lahir");
        tv_thn.setBorder(null);
        tv_thn.setNextFocusableComponent(jButton1);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "FAKULTAS", "JURUSAN", "ALAMAT", "TGL", "BLN", "THN"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        tv_bln.setBackground(new java.awt.Color(229, 229, 229));
        tv_bln.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tv_bln.setForeground(new java.awt.Color(56, 56, 56));
        tv_bln.setToolTipText("Bulan Lahir");
        tv_bln.setBorder(null);
        tv_bln.setNextFocusableComponent(tv_thn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_fakultas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tv_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tv_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tv_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tv_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tv_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tv_thn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tv_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tv_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_fakultas)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tv_thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tv_tgl)
                        .addComponent(tv_bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        nim = tv_nim.getText();
        nama = tv_nama.getText();
        fakultas = cb_fakultas.getSelectedItem().toString();
        jurusan = tv_jurusan.getText();
        alamat = tv_alamat.getText();
        tgl = Integer.parseInt(tv_tgl.getText());
        bln = Integer.parseInt(tv_bln.getText());
        thn = Integer.parseInt(tv_thn.getText());
        
        Object [] data = {nim, nama, fakultas, jurusan, alamat, tgl, bln, thn};
        model.addRow(data);
        
        try{
            Connection koneksi = Konek.getK();
            
            String sql = "INSERT INTO mahasiswa (nim, nama, fakultas, jurusan, alamat, tgl, bln, thn)"
                    + "VALUE (?,?,?,?,?,?,?,?)";
            
            PreparedStatement p = koneksi.prepareStatement(sql);
            p.setString(1, nim);
            p.setString(2, nama);
            p.setString(3, fakultas);
            p.setString(4, jurusan);
            p.setString(5, alamat);
            p.setInt(6, tgl);
            p.setInt(7, bln);
            p.setInt(8, thn);
            
            p.executeUpdate();
            p.close();
            
        }catch(SQLException e){
            System.out.println("error");
        }
        
        tv_nim.setText("");
        tv_nama.setText("");
        tv_jurusan.setText("");
        tv_alamat.setText("");
        tv_tgl.setText("");
        tv_bln.setText("");
        tv_thn.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_fakultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea tv_alamat;
    private javax.swing.JTextField tv_bln;
    private javax.swing.JTextField tv_jurusan;
    private javax.swing.JTextField tv_nama;
    private javax.swing.JTextField tv_nim;
    private javax.swing.JTextField tv_tgl;
    private javax.swing.JTextField tv_thn;
    // End of variables declaration//GEN-END:variables
}
