package simplecalculator;

import core.Calculator;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Muhammad Rosyid Izzulkhaq
 */
public class SimpleCalculatorFrame extends javax.swing.JFrame {
    
    private final String errorTitle = "Error";
    private final String errorMessage = "First Number or Second Number must be filled with number";

    /**
     * Creates new form FormCalculator
     */
    public SimpleCalculatorFrame() {
        initComponents();
        txtFirstNumber.setHorizontalAlignment(SwingConstants.RIGHT);
        txtSecondNumber.setHorizontalAlignment(SwingConstants.RIGHT);
        txtResult.setHorizontalAlignment(SwingConstants.RIGHT);
        txtResult.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        labelFirstNumber = new javax.swing.JLabel();
        txtFirstNumber = new javax.swing.JTextField();
        labelSecondNumber = new javax.swing.JLabel();
        txtSecondNumber = new javax.swing.JTextField();
        btnDivide = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btnSubtract1 = new javax.swing.JButton();
        btnMultiple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");
        setMaximumSize(new java.awt.Dimension(630, 430));
        setMinimumSize(new java.awt.Dimension(630, 430));
        setPreferredSize(new java.awt.Dimension(630, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Simple Calculator");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 630, 60));

        labelResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelResult.setText("Result : ");
        getContentPane().add(labelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 40));

        txtResult.setBackground(new java.awt.Color(51, 51, 51));
        txtResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 340, 40));

        labelFirstNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFirstNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFirstNumber.setText("First Number : ");
        getContentPane().add(labelFirstNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));
        getContentPane().add(txtFirstNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 340, 40));

        labelSecondNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSecondNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSecondNumber.setText("Second Number : ");
        getContentPane().add(labelSecondNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 40));
        getContentPane().add(txtSecondNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 340, 40));

        btnDivide.setBackground(new java.awt.Color(51, 255, 51));
        btnDivide.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivide.setBorderPainted(false);
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 120, 110));

        btnSum.setBackground(new java.awt.Color(255, 51, 51));
        btnSum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSum.setText("+");
        btnSum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSum.setBorderPainted(false);
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        getContentPane().add(btnSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 110));

        btnSubtract1.setBackground(new java.awt.Color(255, 102, 204));
        btnSubtract1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSubtract1.setText("-");
        btnSubtract1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubtract1.setBorderPainted(false);
        btnSubtract1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtract1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtract1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 110));

        btnMultiple.setBackground(new java.awt.Color(51, 51, 255));
        btnMultiple.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMultiple.setText("x");
        btnMultiple.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiple.setBorderPainted(false);
        btnMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultipleActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        String firstNumber = txtFirstNumber.getText();
        String secondNumber = txtSecondNumber.getText();
        if (firstNumber.equals("") || secondNumber.equals("")) {
            JOptionPane.showMessageDialog(null, errorMessage, errorTitle, JOptionPane.ERROR_MESSAGE);
        } else {
            double first = Double.parseDouble(firstNumber);
            double second = Double.parseDouble(secondNumber);
            double result = Calculator.sum(first, second); // Penjumlahan
            txtResult.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnSumActionPerformed

    private void btnSubtract1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtract1ActionPerformed
        String firstNumber = txtFirstNumber.getText();
        String secondNumber = txtSecondNumber.getText();
        if (firstNumber.equals("") || secondNumber.equals("")) {
            JOptionPane.showMessageDialog(null, errorMessage, errorTitle, JOptionPane.ERROR_MESSAGE);
        } else {
            double first = Double.parseDouble(firstNumber);
            double second = Double.parseDouble(secondNumber);
            double result = Calculator.subtract(first, second); // Penjumlahan
            txtResult.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnSubtract1ActionPerformed

    private void btnMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultipleActionPerformed
        String firstNumber = txtFirstNumber.getText();
        String secondNumber = txtSecondNumber.getText();
        if (firstNumber.equals("") || secondNumber.equals("")) {
            JOptionPane.showMessageDialog(null, errorMessage, errorTitle, JOptionPane.ERROR_MESSAGE);
        } else {
            double first = Double.parseDouble(firstNumber);
            double second = Double.parseDouble(secondNumber);
            double result = Calculator.multiple(first, second); // Penjumlahan
            txtResult.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnMultipleActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        String firstNumber = txtFirstNumber.getText();
        String secondNumber = txtSecondNumber.getText();
        if (firstNumber.equals("") || secondNumber.equals("")) {
            JOptionPane.showMessageDialog(null, errorMessage, errorTitle, JOptionPane.ERROR_MESSAGE);
        } else {
            double first = Double.parseDouble(firstNumber);
            double second = Double.parseDouble(secondNumber);
            double result = Calculator.divide(first, second); // Penjumlahan
            txtResult.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnMultiple;
    private javax.swing.JButton btnSubtract1;
    private javax.swing.JButton btnSum;
    private javax.swing.JLabel labelFirstNumber;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelSecondNumber;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField txtFirstNumber;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSecondNumber;
    // End of variables declaration//GEN-END:variables
}
